### ISSUE TITLE
[UC]Manage assignment

### ISSUE THREAD

**Issue by lance-huang-nucloudglobal** [nucloudglobal/lms-ext#10]

**Comment by jbaltazar** [comment]
This is "**DONE**" on my local server but I need to check this in TEST Server. Unfortunately, [http://lmstest.nucloudglobal.net:3000](http://lmstest.nucloudglobal.net:3000) is down at the moment.

**Comment by nucloud-agutierrez** [comment]
QA20150810: QA tested. Fixed in TEST Environment.

1. Login as Academic Manager (sqamanager@domain.com)
2. Click one of the Account e.g(CondeNast)
3. click on of the the Sub account in the account navigation
4. Click on the Sub Account Created (SQA Sub Account 01)
5. Click on one of the Course under the Sub Account (SQA Course 01)
6. In the account navigation, click on Assignments.
7. Create, read, update or delete Assignments(SQA Assignment 01)
8. Create an Assignment Group (SQA Assignment Group 01)
9. Add an assignment in the assignment group (SQA Assignment 01(Academic Manager)
10. Click on the settings of Assignments then check "Weight final grade based on assignment groups"
11. Click on the Quizzes in the course-navigation
12. Create, read, update, delete Quizzes (SQA Quiz 01)
13. Click on the Discussion in the course-navigation
14. Click Create Discussion.
15. Click New Assignment (SQA Assignment (Discussion)

**Comment by nucloud-agutierrez** [comment]
QA20150907: QA tested. Fixed in UAT Environment.

1. Login as Academic Manager (sqamanager@domain.com)
2. Click one of the Account e.g(CondeNast)
3. click on of the the Sub account in the account navigation
4. Click on the Sub Account Created (SQA Sub Account 01)
5. Click on one of the Course under the Sub Account (SQA Course 01)
6. In the account navigation, click on Assignments.
7. Create, read, update or delete Assignments(SQA Assignment 01)
8. Create an Assignment Group (SQA Assignment Group 01)
9. Add an assignment in the assignment group (SQA Assignment 01)
10. Click on the settings of Assignments then check "Weight final grade based on assignment groups"
11. Click on the Quizzes in the course-navigation
12. Create, read, update, delete Quizzes (SQA Quiz 01)
13. Click on the Discussion in the course-navigation
14. Click Create Discussion.
15. Click New Assignment (SQA Assignment Discussion 01)

**Comment by nucloud-agutierrez** [comment]
QA20160127: QA tested. Fixed in PROD Environment.

1. Login as Academic Manager (sqamanager@domain.com)
2. Click one of the Account e.g(CondeNast)
3. click on of the the Sub account in the account navigation
4. Click on the Sub Account Created (SQA Sub Account 01)
5. Click on one of the Course under the Sub Account (SQA Course 01)
6. In the account navigation, click on Assignments.
7. Create, read, update or delete Assignments(SQA Assignment 01)
8. Create an Assignment Group (SQA Assignment Group 01)
9. Add an assignment in the assignment group (SQA Assignment 01)
10. Click on the settings of Assignments then check "Weight final grade based on assignment groups"
11. Click on the Quizzes in the course-navigation
12. Create, read, update, delete Quizzes (SQA Quiz 01)
13. Click on the Discussion in the course-navigation
14. Click Create Discussion.
15. Click New Assignment (SQA Assignment Discussion 01)
