### ISSUE TITLE
[UC]Manage syllabus

### ISSUE THREAD

**Issue by lance-huang-nucloudglobal** [nucloudglobal/lms-ext#11]

**Comment by jbaltazar** [comment]
This is "**DONE**" on my local server but I need to check this in TEST Server. Unfortunately, [http://lmstest.nucloudglobal.net:3000](http://lmstest.nucloudglobal.net:3000) is down at the moment.

**Comment by nucloud-agutierrez** [comment]
QA20150807: QA tested. Fixed in TEST Environment.

**Syllabus (Course Level)**
**Roles: Teacher, Academic executive, Academic manager**

1. Login as Academic Manager (sqamanager@domain.com)
2. Click one of the Account e.g(CondeNast)
3. click on of the the Sub account in the account navigation
4. Click on the Sub Account Created (SQA Sub Account 01)
5. Click on one of the Course under the Sub Account (SQA Course 01)
6. In the account navigation, click on Syllabus
7. Read or update Syllabus.
8. Edit Syllabus description.
9. Verify displayed items (SQA Assignment 01, SQA Quiz 01, Calendar and weighted assignment groups).

**Comment by nucloud-agutierrez** [comment]
QA20150807: QA tested. Fixed in TEST Environment.

**Syllabus (Course Level)**
**Roles: Teacher, Academic executive, Academic manager**

1. Login as Academic Manager (sqamanager@domain.com)
2. Click one of the Account e.g(CondeNast)
3. click on of the the Sub account in the account navigation
4. Click on the Sub Account Created (SQA Sub Account 01)
5. Click on one of the Course under the Sub Account (SQA Course 01)
6. In the account navigation, click on Syllabus
7. Read or update Syllabus.
8. Edit Syllabus description.
9. Verify displayed items (Assignment, SQA Assignment Group 01, Calendar and weighted assignment groups).

**Comment by nucloud-agutierrez** [comment]
QA20160127: QA tested. Fixed in UAT Environment.

**Syllabus (Course Level)**
**Roles: Teacher, Academic executive, Academic manager**

1. Login as Academic Manager (sqamanager@domain.com)
2. Click one of the Account e.g(CondeNast)
3. click on of the the Sub account in the account navigation
4. Click on the Sub Account Created (SQA Sub Account 01)
5. Click on one of the Course under the Sub Account (SQA Course 01)
6. In the account navigation, click on Syllabus
7. Read or update Syllabus.
8. Edit Syllabus description.
9. Verify displayed items (SQA Assignment Discussion 01, SQA Assignment 01, Calendar and weighted assignment groups).
