### ISSUE TITLE
[UC]View course announcement

### ISSUE THREAD

**Issue by lance-huang-nucloudglobal** [nucloudglobal/lms-ext#12]

**Comment by nucloud-agutierrez** [comment]
QA20150810: QA tested. Not Fixed.

**Steps to Reproduce**

1. Login as Academic Manager (sqamanager@domain.com)
2. Click one of the Account e.g(CondeNast)
3. Click on of the the Sub account in the account navigation
4. Click on the Sub Account Created (SQA Sub Account 01)
5. Click on one of the Course under the Sub Account (SQA Course 01)
6. In the account navigation, click on Announcements.
7. View All Announcements
8. Select an Announcement then click settings.
9. Click "Mark all as read"
10. Search an Announcements via(Title, Author, Body or Entry)

**Expected Result:**
- User can search the available announcement base on the given search criteria.

**Actual Result: **
- User was not given a search result after searching using the given search criteria.

**see attached test evidences**

![search announcement via entry](https://cloud.githubusercontent.com/assets/8049330/9157375/ca7e842a-3f2d-11e5-9f1f-66cce3b31b8c.png)

![search announcement via author](https://cloud.githubusercontent.com/assets/8049330/9157376/ca81e214-3f2d-11e5-8dc2-2f59fc6a354c.png)

![search announcment via title](https://cloud.githubusercontent.com/assets/8049330/9157377/cab57f48-3f2d-11e5-866b-30eba87eb2ff.png)

**Comment by jbaltazar** [comment]
Hi Team,

For the Announcement Searching, LMS is using "Like" method instead of "equal" method.
![announcement_searching](https://cloud.githubusercontent.com/assets/7844693/9158177/65b14d36-3f44-11e5-9355-4efac336387e.png)



Thank you.

**Comment by lance-huang-nucloudglobal** [comment]
per discussion in skype
search "sqa announcement 01" means:

SEARCH: "sqa announcement 01"
FOR: Title OR Body OR Author
CONTAINS
    "sqa" OR "announcement" OR "01"

letter case in search is not sensitive

**Comment by nucloud-agutierrez** [comment]
QA20150810: QA Tested. Fixed in TEST Environment.

Steps to Reproduce

1. Login as Academic Manager (sqamanager@domain.com)
2. Click one of the Account e.g(CondeNast)
3. Click on of the the Sub account in the account navigation
4. Click on the Sub Account Created (SQA Sub Account 01)
5. Click on one of the Course under the Sub Account (SQA Course 01)
6. In the account navigation, click on Announcements.
7. View All Announcements
8. Select an Announcement then click settings.
9. Click "Mark all as read"
10. Search for an Announcement eg. (SQA Announcement 01).

**Comment by nucloud-agutierrez** [comment]
QA20150810: QA Tested. Fixed in UAT Environment.

**Steps to Reproduce**

1. Login as Academic Manager (sqamanager@domain.com)
2. Click one of the Account e.g(CondeNast)
3. Click on of the the Sub account in the account navigation
4. Click on the Sub Account Created (SQA Sub Account 01)
5. Click on one of the Course under the Sub Account (SQA Course 01)
6. In the account navigation, click on Announcements.
7. View All Announcements
8. Select an Announcement then click settings.
9. Click "Mark all as read"
10. Search for an Announcement eg. (SQA Announcement 01).

**Comment by nucloud-agutierrez** [comment]
QA20150907: QA Tested. Fixed in UAT Environment.

**Steps to Reproduce**

1. Login as Academic Manager (sqamanager@domain.com)
2. Click one of the Account e.g(CondeNast)
3. Click on of the the Sub account in the account navigation
4. Click on the Sub Account Created (SQA Sub Account 01)
5. Click on one of the Course under the Sub Account (SQA Course 01)
6. In the account navigation, click on Announcements.
7. View All Announcements
8. Select an Announcement then click settings.
9. Click "Mark all as read"
10. Search for an Announcement eg. (SQA Announcement 01).
