### ISSUE TITLE
[UC]Manage account role

### ISSUE THREAD

**Issue by lance-huang-nucloudglobal** [nucloudglobal/lms-ext#15]
FS: https://trello.com/c/wFaw171m/4-s-01-s-10-s-21-functional-specification

**Comment by jbaltazar** [comment]
I initiate to start this UC where @apetitnucloud is look like busy and not answering my skype message.

CC: @lance-huang-nucloudglobal

**Comment by nucloud-agutierrez** [comment]
QA20150813: QA tested. Fixed in TEST Environment.

Steps:
1.	Login as a Top Account role (agutierrez@nucloudglobal.com)
2.	Click on one of the account (CondeNast)
3.	Click on the the Permissions in account-navigation
4.	Click on the Account Roles tab
5.	Create, read, update delete role within current account (SQA Academic Manager, SQA Academic Director, SQA Academic Executive)

**Comment by nucloud-agutierrez** [comment]
QA20150907: QA tested. Fixed in UAT Environment.

**Steps:**

1.	Login as a Top Account role (agutierrez@nucloudglobal.com)
2.	Click on one of the account (CondeNast)
3.	Click on the the Permissions in account-navigation
4.	Click on the Account Roles tab
5.	Create, read, update delete role within current account (SQA Academic Manager, SQA Academic Director, SQA Academic Executive)

**Comment by nucloud-agutierrez** [comment]
QA20160127: QA tested. Fixed in PROD Environment.

**Steps:**

1.	Login as a Top Account role (agutierrez@nucloudglobal.com)
2.	Click on one of the account (CondeNast)
3.	Click on the the Permissions in account-navigation
4.	Click on the Account Roles tab
5.	Create, read, update delete role within current account (SQA Academic Manager, SQA Academic Director, SQA Academic Executive)
