### ISSUE TITLE
[UC]Manage account role permission

### ISSUE THREAD

**Issue by lance-huang-nucloudglobal** [nucloudglobal/lms-ext#16]
FS: https://trello.com/c/wFaw171m/4-s-01-s-10-s-21-functional-specification

**Comment by jbaltazar** [comment]
I initiate to start this UC where @apetitnucloud is look like busy and not answering my skype message.

CC: @lance-huang-nucloudglobal

**Comment by nucloud-agutierrez** [comment]
QA20150817: QA tested. Fixed in TEST Environment.

1. Login as Academic Manager (sqamanager@domain.com)
2. Click one of the Account e.g(CondeNast)
3. Click on of the the Sub account in the account navigation
4. Click on the Sub Account Created (SQA Sub Account 01)
5. Click on one of the Course under the Sub Account (SQA Course 01)
6. In the account navigation, click on Permissions.
7. In the Permissions, click on the Account Roles tab
7. Create, read, update or delete role permission within current account (Add Some Admin Permissions for Academic Manager, Academic Director and Academic Executive)

**Comment by lance-huang-nucloudglobal** [comment]
@nucloud-agutierrez 
I'd like to request you to test and record
1. The permission item is not so self-explaining named
2. describe the what will happen after a permission item is swtiched on/off

Pls make an excel sheet to record your info, thx

**Comment by lance-huang-nucloudglobal** [comment]
@nucloud-agutierrez 
Joy, I made an example sheet to support you for this, the reason this sheet is also in Backlog trello card is it shares part of the information from backlog
https://trello-attachments.s3.amazonaws.com/556bdadbae6f6ced74c60837/557fdc5f33c6e53869b947c4/f04a9d3d3638d8f96b86f086068be0d9/%5BConde_Nast_LMS%5DPermission_setting_20150819_V0.5.2.xlsx

Purpose:
Identify in order to perform the UC, which permission needs to be ticked as "Y"

Suggested way of doing:
1. For each role, for each UC, one by One, go through the permission columns in sheet and choose minimum Y according to the self-explanation permission name
2. Go to LMS to assign those Y to the role
3. Check in LMS to see if the UC can be done by the role with the current permission setting
4. If sth can not be done, add Y to more permission item, be careful only add as little permission as possible every time

Loop in 1~4 until 
A. One by one, every UC can be done by the role correctly
B. Only focus on the UC has been in TEST ready status

It will be a long process so pls be patient and careful when doing this, there's no explicit online document can support us for this. It will be slow at the beginning and will be faster and faster after a period. Pls spend enough time on it.

Since the Row of the excel has to be synced with Backlog and UCs in backlog will increase, you and me need to have a "Rule" for how to update it if new lines(UC) need to inserted. In order not to break your data in sheet, I will inform you to pause updating the sheet right before I modify UCs, then I will get latest version from your side and insert new lines into it, so that your existing data wont be broken. 

cheers

**Comment by nucloud-agutierrez** [comment]
QA20150914: QA tested. Fixed in TEST Environment.

1. Login as Academic Manager (sqamanager@domain.com)
2. Click one of the Account e.g(CondeNast)
3. Click on of the the Sub account in the account navigation
4. Click on the Sub Account Created (SQA Sub Account 01)
5. Click on one of the Course under the Sub Account (SQA Course 01)
6. In the account navigation, click on Permissions.
7. In the Permissions, click on the Account Roles tab
7. Create, read, update or delete role permission within current account (Add Some Admin Permissions for Academic Manager, Academic Director and Academic Executive)

**Comment by nucloud-agutierrez** [comment]
QA2016: QA tested. Fixed in PROD Environment.

1. Login as Academic Manager (sqamanager@domain.com)
2. Click one of the Account e.g(CondeNast)
3. Click on of the the Sub account in the account navigation
4. Click on the Sub Account Created (SQA Sub Account 01)
5. Click on one of the Course under the Sub Account (SQA Course 01)
6. In the account navigation, click on Permissions.
7. In the Permissions, click on the Account Roles tab
7. Create, read, update or delete role permission within current account (Add Some Admin Permissions for Academic Manager, Academic Director and Academic Executive)
