### ISSUE TITLE
[UC]Manage course role permission

### ISSUE THREAD

**Issue by lance-huang-nucloudglobal** [nucloudglobal/lms-ext#19]
FS: https://trello.com/c/wFaw171m/4-s-01-s-10-s-21-functional-specification

**Comment by jbaltazar** [comment]
I initiate to start this UC where @apetitnucloud is look like busy and not answering my skype message.

CC: @lance-huang-nucloudglobal

**Comment by nucloud-agutierrez** [comment]
QA20150817: QA Tested. Fixed in TEST Environment.

1. Login as Academic Manager (sqamanager@domain.com)
2. Click one of the Account e.g(CondeNast)
3. Click on of the the Sub account in the account navigation
4. Click on the Sub Account Created (SQA Sub Account 01)
5. Click on one of the Course under the Sub Account (SQA Course 01)
6. In the account navigation, click on Permissions.
7. In the Permissions, click on the Course Roles tab
8. Create, read, update or delete role permission within current account (Add or Delete Some Course & Account Permissions for SQA Student and SQA Teacher)

**Comment by lance-huang-nucloudglobal** [comment]
@nucloud-agutierrez 
see https://github.com/nucloudglobal/lms-ext/issues/16#issuecomment-131658625

**Comment by nucloud-agutierrez** [comment]
QA20150910: QA Tested. Fixed in UAT Environment.

1. Login as Academic Manager (sqamanager@domain.com)
2. Click one of the Account e.g(CondeNast)
3. Click on of the the Sub account in the account navigation
4. Click on the Sub Account Created (SQA Sub Account 01)
5. Click on one of the Course under the Sub Account (SQA Course 01)
6. In the account navigation, click on Permissions.
7. In the Permissions, click on the Course Roles tab
8. Create, read, update or delete role permission within current account (Add or Delete Some Course & Account Permissions for SQA Student and SQA Teacher)

**Comment by nucloud-agutierrez** [comment]
QA20160127: QA Tested. Fixed in PROD Environment.

1. Login as Academic Manager (sqamanager@domain.com)
2. Click one of the Account e.g(CondeNast)
3. Click on of the the Sub account in the account navigation
4. Click on the Sub Account Created (SQA Sub Account 01)
5. Click on one of the Course under the Sub Account (SQA Course 01)
6. In the account navigation, click on Permissions.
7. In the Permissions, click on the Course Roles tab
8. Create, read, update or delete role permission within current account (Add or Delete Some Course & Account Permissions for SQA Student and SQA Teacher)
