### ISSUE TITLE
[UC]Manage grading scheme

### ISSUE THREAD

**Issue by lance-huang-nucloudglobal** [nucloudglobal/lms-ext#2]

**Comment by nucloud-agutierrez** [comment]
QA20150728: QA tested. Fixed in TEST Environment.

*see attached test evidences*

![create grading schemes](https://cloud.githubusercontent.com/assets/8049330/8922494/3706bb20-3516-11e5-99ce-67047c949abe.png)

![edit grading scheme](https://cloud.githubusercontent.com/assets/8049330/8922496/3a7ebf8c-3516-11e5-9ece-b6b898bf6999.png)

![delete grading scheme](https://cloud.githubusercontent.com/assets/8049330/8922498/3f04d5dc-3516-11e5-8cc4-9c2d724bc096.png)

![course level grading scheme](https://cloud.githubusercontent.com/assets/8049330/8922500/44346f22-3516-11e5-855a-922ec34cee40.png)

![course level view - edit grading scheme](https://cloud.githubusercontent.com/assets/8049330/8922508/59306fca-3516-11e5-877d-7d0813f3184a.png)

![course level already defined grading scheme](https://cloud.githubusercontent.com/assets/8049330/8922510/5bc2c878-3516-11e5-9dcf-b1682c936019.png)

**Comment by nucloud-agutierrez** [comment]
QA20150728: QA tested. Fixed in TEST Environment.

Grading Scheme (Sub Account)

1. Login as Top Account (agutierrez@nucloudglobal.com)
2. Click one of the Account e.g(CondeNast)
2.5 click on of the the Sub account
3. In the account navigation, click on Grading.
4. Create, read, update or delete grading.

Grading Scheme (Course)

1. Login a teacher's role (sqa02@teacher.com)
2. Click on one of the Course under the Sub Account "where the sub-account level grading scheme has been created"
3. Click on the Settings of the course
4. Under the course details tab, click 'View/edit Grading Scheme' link.
5. Click 'Manage Grading Schemes' link
6. Use grading scheme which has been created, but do not create a new one

**Comment by lance-huang-nucloudglobal** [comment]
@nucloud-agutierrez 
recommend to fill your steps with data, e.g.
click on of the the Sub account -> click Sub account - SQA Sub Account 01

Click on one of the Course  - "Course Name" under the Sub Account "where the sub-account level grading scheme has been created"

**Comment by nucloud-agutierrez** [comment]
QA20150728: QA tested. Fixed in UAT Environment.

**Grading Scheme (Sub Account)**

1. Login as Academic Manager (sqamanager@domain.com)
2. Click one of the Account e.g(CondeNast)
3. Click on of the the Sub account in the account navigation
4. Click on the Sub Account Created (SQA Sub Account 01)
5. In the account navigation, click on Grading.
6. Create, read, update or delete grading (SQA Grading Schemes 01)

**Grading Scheme (Course)**

1. Login as Academic Manager (sqamanager@domain.com)
2. Click on one of the Course under the Sub Account "where the sub-account level grading scheme has been created" (SQA Course 01)
3. Click on the Settings of the course
4. Click 'Manage Grading Schemes' link
5. Use grading scheme which has been created, but not create a new one (SQA Grading Schemes 01)

**Comment by nucloud-agutierrez** [comment]
QA20160127: QA tested. Fixed in PROD Environment.

**Grading Scheme (Sub Account)**

1. Login as Academic Manager (sqamanager@domain.com)
2. Click one of the Account e.g(CondeNast)
3. Click on of the the Sub account in the account navigation
4. Click on the Sub Account Created (SQA Sub Account01)
5. In the account navigation, click on Grading.
6. Create, read, update or delete grading (SQA Grading Schemes01)

**Grading Scheme (Course)**

1. Login as Academic Manager (sqamanager@domain.com)
2. Click on one of the Course under the Sub Account "where the sub-account level grading scheme has been created" (SQA Course01)
3. Click on the Settings of the course
4. Click 'Manage Grading Schemes' link
5. Use grading scheme which has been created, but not create a new one (SQA Grading Schemes01)
