### ISSUE TITLE
[UC]Publish course info

### ISSUE THREAD

**Issue by lance-huang-nucloudglobal** [nucloudglobal/lms-ext#21]
https://trello.com/c/9pU5wmRO/15-s-07-functional-specification

**Comment by nucloud-agutierrez** [comment]
QA20150826: QA tested. Fixed in TEST Environment.

**Steps:**

1. Login as Academic Manager (sqamanager@domain.com)
2. Click one of the Account e.g(CondeNast)
3. Click one of the Sub account in the account navigation
4. Click on the Sub Account Created (SQA Sub Account 01)
5. Click on one of the Course under the Sub Account (SQA Course 01)
6. In course-navigation click on Home, Modules, Assignments, Quizzes, Discussions, Pages, or Files.
7. Click on the Publish icon.

**Comment by nucloud-agutierrez** [comment]
QA20150907: QA tested. Fixed in UAT Environment.

**Steps:**

1. Login as Academic Manager (sqamanager@domain.com)
2. Click one of the Account e.g(CondeNast)
3. Click one of the Sub account in the account navigation
4. Click on the Sub Account Created (SQA Sub Account 01)
5. Click on one of the Course under the Sub Account (SQA Course 01)
6. In course-navigation click on Home, Modules, Assignments, Quizzes, Discussions, Pages, or Files.
7. Click on the Publish icon.

**Comment by nucloud-agutierrez** [comment]
QA20160127: QA tested. Fixed in PROD Environment.

**Steps:**

1. Login as Academic Manager (sqamanager@domain.com)
2. Click one of the Account e.g(CondeNast)
3. Click one of the Sub account in the account navigation
4. Click on the Sub Account Created (SQA Sub Account01)
5. Click on one of the Course under the Sub Account (SQA Course01)
6. In course-navigation click on Home, Modules, Assignments, Quizzes, Discussions, Pages, or Files.
7. Click on the Publish icon.
