### ISSUE TITLE
[UC]Send global announcement

### ISSUE THREAD

**Issue by lance-huang-nucloudglobal** [nucloudglobal/lms-ext#22]
https://trello.com/c/uXqPCHLk/16-s-11-functional-specification

**Comment by jbaltazar** [comment]
Note:
Everything is working for the top account sending global announcement to all or specific course and account roles. 

![top_account](https://cloud.githubusercontent.com/assets/7844693/9348431/2bca65ae-4669-11e5-85a2-c0b87cb9ed8c.png)

Except for sending global announcement to specific course and account roles under sub-account.
![sub_account_roles](https://cloud.githubusercontent.com/assets/7844693/9348682/19f9f52a-466d-11e5-956c-92b35a6faaf7.jpg)

**Comment by jbaltazar** [comment]
In Summary:
There is no way to send a global announcement for specific "Account Roles" under Sub Account. LMS can only send for specific "Account Roles" if the roles is being created under Top Account. Kindly refere to the screenshot that I post a while ago.

**Comment by nucloud-agutierrez** [comment]
QA20150826: QA tested. Fixed.

*Steps:*

1. Login as Account Admin (agutierrez@nucloudglobal.com)
2. Click one of the Account e.g(CondeNast)
3. In the Account Navigation, click on Settings
4. In the Settings, click on Announcement tab
5. Create, read, delete global announcement (SQA Global Announcement)

**Comment by nucloud-agutierrez** [comment]
QA20150826: QA tested. Fixed in TEST Environment.

**Steps:**

1. Login as Account Admin (agutierrez@nucloudglobal.com)
2. Click one of the Account e.g(CondeNast)
3. In the Account Navigation, click on Settings
4. In the Settings, click on Announcement tab
5. Create, read, delete global announcement e.g(SQA Announcement 01)

**Comment by nucloud-agutierrez** [comment]
QA20160127: QA tested. Fixed in PROD Environment.

**Steps:**

1. Login as Account Admin (agutierrez@nucloudglobal.com)
2. Click one of the Account e.g(CondeNast)
3. In the Account Navigation, click on Settings
4. In the Settings, click on Announcement tab
5. Create, read, delete global announcement e.g(SQA Global Announcement)
