### ISSUE TITLE
[UC]View global announcement

### ISSUE THREAD

**Issue by lance-huang-nucloudglobal** [nucloudglobal/lms-ext#23]
https://trello.com/c/MojolvHM/18-s-34-functional-specification

**Comment by nucloud-agutierrez** [comment]
QA20150826: QA tested. Fixed in TEST Environment.

1. Login as Account Admin (agutierrez@nucloudglobal.com)
2. Click one of the Account e.g(CondeNast)
3. In the Account Navigation, click on Settings
4. In the Settings, click on Announcement tab
5. Create, read, delete global announcement (SQA Global Announcement 2).
6. Go to LMS Dashboard, user can view the created announcement since the user was set to receive and view the announcement.

**Comment by nucloud-agutierrez** [comment]
QA20150910: QA tested. Fixed in UAT Environment.

**Steps:**
1. Login as Account Admin (agutierrez@nucloudglobal.com)
2. Click one of the Account e.g(CondeNast)
3. In the Account Navigation, click on Settings
4. In the Settings, click on Announcement tab
5. Create, read, delete global announcement (SQA Announcement 01).
6. Go to LMS Dashboard, user can view the created announcement since the user was set to receive and view the announcement.

**Comment by nucloud-agutierrez** [comment]
QA20160127: QA tested. Fixed in PROD Environment.

**Steps:**
1. Login as Account Admin (agutierrez@nucloudglobal.com)
2. Click one of the Account e.g(CondeNast)
3. In the Account Navigation, click on Settings
4. In the Settings, click on Announcement tab
5. Create, read, delete global announcement (SQA Global Announcement).
6. Go to LMS Dashboard, user can view the created announcement since the user was set to receive and view the announcement.
