### ISSUE TITLE
[UC]Manage ePortfolio

### ISSUE THREAD

**Issue by lance-huang-nucloudglobal** [nucloudglobal/lms-ext#25]
https://trello.com/c/z4XC9M1t/17-s-33-functional-specification

**Comment by nucloud-agutierrez** [comment]
1) Login as Student
2) Click “Settings” before “Logout” link
3) Click “ePortfolios” link under Account Navigation
4) Click “Create an ePortfolio” button
5) Write ePortfolio’s Name and check the checkbo for “Make it Public”
6) Click  the created ePortfolio
7)  Click the link “Organize/Manage Pages” in the right corner of the page near to “Home” link
8) Click the page name to edit ePortfolios page content
9) click the “Edit this Page” button to show to add content

**Comment by nucloud-agutierrez** [comment]
QA20151102: QA tested. Fixed in UAT Environment.

1) Login as Student (dev_student@domain.com)
2) Click “Settings” before “Logout” link
3) Click “ePortfolios” link under Account Navigation
4) Click “Create an ePortfolio” button
5) Write ePortfolio’s Name and check the checkbo for “Make it Public”
6) Click the created ePortfolio
7) Click the link “Organize/Manage Pages” in the right corner of the page near to “Home” link
8) Click the page name to edit ePortfolios page content
9) click the “Edit this Page” button to show to add content

**Comment by nucloud-agutierrez** [comment]
QA20160127: QA tested. Fixed in PROD Environment.

1) Login as Student (sqastudent@domain.com)
2) Click “Settings” before “Logout” link
3) Click “ePortfolios” link under Account Navigation
4) Click “Create an ePortfolio” button
5) Write ePortfolio’s Name and check the checkbo for “Make it Public”
6) Click the created ePortfolio
7) Click the link “Organize/Manage Pages” in the right corner of the page near to “Home” link
8) Click the page name to edit ePortfolios page content
9) click the “Edit this Page” button to show to add content
