### ISSUE TITLE
[UC]Manage outcome

### ISSUE THREAD

**Issue by lance-huang-nucloudglobal** [nucloudglobal/lms-ext#3]

**Comment by nucloud-agutierrez** [comment]
QA20150729: QA tested. Fixed in TEST Environment.

Steps:

Outcomes (Sub Account)

1. Login as Top Account (agutierrez@nucloudglobal.com)
2. Click one of the Account e.g(CondeNast)
3. click on one of the the Sub account
4. In the account navigation, click on Outcomes.
5. Create, read, update or delete grading.

Outcomes (Course)

1. Login a teacher's role (sqa02@teacher.com)
2. Click on one of the Course under the Sub Account "where the sub-account level outcome has been created"
3. Click on the Outcomes in the course-navigation
4. Click Find button
5. User find a outcome already defined at account level and import it into current course to use.

**Comment by nucloud-agutierrez** [comment]
QA20150903: QA tested. Fixed in UAT Environment.

Steps:

**Outcomes (Sub Account)**

1. Login as Academic Manager (sqamanager@domain.com)
2. Click on the Account (CondeNast)
4. Click on the Sub Account under the Account (SQA Sub Account 01)
5. In the sub account navigation, click on Outcomes.
6. Create, read, update or delete outcomes (SQA Outcome 01)

**Outcomes (Course)**

1. Login as Academic Manager (sqamanager@domain.com)
2. Click on one of the Course under the Sub Account "where the sub-account level outcome has been created" (SQA Course 01)
3. Click on the Outcomes in the course-navigation
4. Click Find button
5. User find a outcome already defined at account level and import it into current course to use (SQA Outcome 01).

**Comment by nucloud-agutierrez** [comment]
QA20160127: QA tested. Fixed in PROD Environment.

Steps:

**Outcomes (Sub Account)**

1. Login as Academic Manager (sqamanager@domain.com)
2. Click on the Account (CondeNast)
4. Click on the Sub Account under the Account (SQA Sub Account 01)
5. In the sub account navigation, click on Outcomes.
6. Create, read, update or delete outcomes (SQA Outcome 01)

**Outcomes (Course)**

1. Login as Academic Manager (sqamanager@domain.com)
2. Click on one of the Course under the Sub Account "where the sub-account level outcome has been created" (SQA Course 01)
3. Click on the Outcomes in the course-navigation
4. Click Find button
5. User find a outcome already defined at account level and import it into current course to use (SQA Outcome 01).
