### ISSUE TITLE
[UC]View student progress in module

### ISSUE THREAD

**Issue by lance-huang-nucloudglobal** [nucloudglobal/lms-ext#31]
FS: https://trello.com/c/c31MTfXW/22-s-05-s-16-s-28-s-40-functional-specification

**Comment by jbaltazar** [comment]
This is default feature of Canvas LMS, we can start testing this UC in our SQA and UAT Server without the help of TL - @apetitnucloud for deployment.

**Comment by nucloud-agutierrez** [comment]
QA20151127: QA tested. Fixed.

1. Login as a teacher (sqateacher@domain.com)
- User will see all account in the global-navigation
- Different users see different accounts depending on which hierarchy level the user is located in
2. User click on [Courses] in account-navigation
3. User click on [Modules] in course-navigation
4. User click on [View Progress] button
- User can see each student progress on every module

**Comment by ajmgutierrez** [comment]
QA20151127: QA tested. Fixed in UAT Environment.

1. Login as a teacher (sqateacher01@domain.com)
- User will see all account in the global-navigation
- Different users see different accounts depending on which hierarchy level the user is located in
2. User click on [Courses] in account-navigation
3. User click on [Modules] in course-navigation
4. User click on [View Progress] button
- User can see each student progress on every module

**Comment by nucloud-agutierrez** [comment]
QA20151127: QA tested. Fixed in UAT Environment.

1. Login as a teacher (sqateacher@domain.com)
    - User will see all account in the global-navigation
    - Different users see different accounts depending on which hierarchy level the user is located in
2. User click on [Courses] in account-navigation
3. User click on [Modules] in course-navigation
4. User click on [View Progress] button
   - User can see each student progress on every module
