### ISSUE TITLE
[UC]View student graded course activity

### ISSUE THREAD

**Issue by lance-huang-nucloudglobal** [nucloudglobal/lms-ext#32]
FS: https://trello.com/c/c31MTfXW/22-s-05-s-16-s-28-s-40-functional-specification

**Comment by jbaltazar** [comment]
Everything is working fine where this one is a default feature of Canvas LMS, However there is a major issue when it comes in layout.

<b>Issue</b>
Some iframe is attaching/adding the custom footer.
See Screenshot: 
![viewstudentgradedcourseactivity](https://cloud.githubusercontent.com/assets/7844693/11331774/f8e14afe-91f9-11e5-9a79-a9533a61a299.png)

<b>Solution:</b>
I modified footer content and css file to fix this issue.
[Pull Request Information](https://github.com/nucloudglobal/lms/pull/12)

<b>Note</b>
With the modification of footer and CSS. This will be label as <b>Code Review</b> and merge to <b>Dev</b> branch before the SQA can test it.

CC: @nucloud-agutierrez @apetitnucloud

**Comment by nucloud-agutierrez** [comment]
QA20160113: QA tested. Fixed in Test Environment.

a) User will see all account in the global-navigation
  -  Different users see different accounts depending on which hierarchy level the user is located in
￼b) User click on [Courses] in account-navigation
c) User click on [People] in course-navigation
d) User click on student name (Gutierrez, Amalia Joy)
e) User click on [Grades for ‘student name’] button in right-panel 
f) User will see a information table of this student’s
   - Name (of the assignment)
   - Due
   - Score
   - Out of
   - Comment, scoring detail, rubric result
   - Summary of each assignment group and total of assignment
g) User can click on the name (of the assignment) to see the detail of the this student’s action in this course activity

**Comment by nucloud-agutierrez** [comment]
QA20160127: QA tested. Fixed in PROD Environment.

a) User will see all account in the global-navigation
  -  Different users see different accounts depending on which hierarchy level the user is located in

￼b) User click on [Courses] in account-navigation

c) User click on [People] in course-navigation

d) User click on student name (SQA Student01)

e) User click on [Grades for ‘student name’] button in right-panel 

f) User will see a information table of this student’s
   - Name (of the assignment)
   - Due
   - Score
   - Out of
   - Comment, scoring detail, rubric result
   - Summary of each assignment group and total of assignment

g) User can click on the name (of the assignment) to see the detail of the this student’s action in this course activity

**Comment by lance-huang-nucloudglobal** [comment]
@nucloud-agutierrez @apetitnucloud 
Hum...this ticket just go to PROD from TEST directly with out being testing on UAT~?
not really recommended.
