### ISSUE TITLE
[UC]Manage discussion

### ISSUE THREAD

**Issue by lance-huang-nucloudglobal** [nucloudglobal/lms-ext#34]
FS: https://trello.com/c/FXz3CUfr/23-s-06-s-18-s-26-functional-specification

**Comment by jbaltazar** [comment]
This is default feature of Canvas LMS. I'm already done testing and checking this UC for both Local VM and SQA Server.

<b>SQA</b> can start testing this UC after I finish the [Word Filter UC](https://github.com/nucloudglobal/lms-ext/issues/35) where this two UC is connected to each other

**Comment by nucloud-agutierrez** [comment]
QA20151127: QA tested. Reopened.

1. Login as Academic Manager (sqamanager@domain.com)
- User will see all account in the global-navigation
- Different users see different accounts depending on which hierarchy level the user is located in
2. User click on [Courses] in account-navigation
3. User click on [Discussions ] in course-navigation
4. User see different discussions, depend on the necessity, user can set:
- Stop student from posting replies
- Edit and delete a discussion and discussion post
- Allow to “Like” the discussion
- Allow student to attach file in discussion
- Allow student to start a new discussion
- Allow student to edit and delete own discussion post

*Actual Result*
- User has no way to set student to stop posting replies and allow to “like” the discussion.

![uc34_reopened](https://cloud.githubusercontent.com/assets/8049330/11432397/9baaaf0a-94e8-11e5-9f54-490ada2ead3a.png)

**Comment by lance-huang-nucloudglobal** [comment]
@nucloud-agutierrez 
To Stop student from posting replies:
![image](https://cloud.githubusercontent.com/assets/8621588/11432800/22dfe56a-94f0-11e5-9289-90f324f5b859.png)
Pls test if new post can be added after "Close for comments", refer this to http://guides.instructure.com/m/4152/l/123824-how-do-i-close-a-discussion-for-comments-in-my-course

Allow to “Like” the discussion:
In Discussion -> Edit
![image](https://cloud.githubusercontent.com/assets/8621588/11432862/3213cc4e-94f1-11e5-947b-7a2b735a47ed.png)
Refer this to http://guides.instructure.com/m/4152/l/348630-how-do-i-allow-students-to-like-replies-in-a-discussion

CC @jbaltazar

**Comment by jbaltazar** [comment]
As per @lance-huang-nucloudglobal comment above kindly follow those step for "<i>Stop posting replies and allow to 'like' the discussion</i>" @nucloud-agutierrez

**Comment by nucloud-agutierrez** [comment]
QA20151202: QA tested. Fixed in Test Environment.

1. Login as Academic Manager (sqamanager@domain.com)
  - User will see all account in the global-navigation
  - Different users see different accounts depending on which hierarchy level the user is located in
2. User click on [Courses] in account-navigation
3. User click on [Discussions ] in course-navigation
4. User see different discussions, depend on the necessity, user can set:
  - Stop student from posting replies
  - Edit and delete a discussion and discussion post
  - Allow to “Like” the discussion
  - Allow student to attach file in discussion
  - Allow student to start a new discussion
  - Allow student to edit and delete own discussion post

**Comment by nucloud-agutierrez** [comment]
QA20151202: QA tested. Fixed in UAT Environment.

1. Login as Academic Manager (sqamanager@domain.com)
  - User will see all account in the global-navigation
  - Different users see different accounts depending on which hierarchy level the user is located in
2. User click on [Courses] in account-navigation
3. User click on [Discussions ] in course-navigation
4. User see different discussions, depend on the necessity, user can set:
  - Stop student from posting replies
  - Edit and delete a discussion and discussion post
  - Allow to “Like” the discussion
  - Allow student to attach file in discussion
  - Allow student to start a new discussion
  - Allow student to edit and delete own discussion post

**Comment by nucloud-agutierrez** [comment]
QA20160127: QA tested. Fixed in PROD Environment.

1. Login as Academic Manager (sqamanager@domain.com)
  - User will see all account in the global-navigation
  - Different users see different accounts depending on which hierarchy level the user is located in
2. User click on [Courses] in account-navigation
3. User click on [Discussions ] in course-navigation
4. User see different discussions, depend on the necessity, user can set:
  - Stop student from posting replies
  - Edit and delete a discussion and discussion post
  - Allow to “Like” the discussion
  - Allow student to attach file in discussion
  - Allow student to start a new discussion
  - Allow student to edit and delete own discussion post
