### ISSUE TITLE
[UC]Manage assignmentS  - submission

### ISSUE THREAD

**Issue by lance-huang-nucloudglobal** [nucloudglobal/lms-ext#36]
FS: https://trello.com/c/RxWdbP59/26-s-37-functional-specification

**Comment by jbaltazar** [comment]
This is default feature of Canvas LMS, we can start testing this UC in our TEST ready without the help of TL - @apetitnucloud

**Comment by nucloud-agutierrez** [comment]
QA20151123: QA tested. Fixed.

1. Login as Teacher (sqateacher01@domain.com)
2. Create Assignment with special option for (Text Entry, Upload, WebURL, etc)
3. Login as Student (condenastlmstest-three@yahoo.com.ph)
4.Tthe created assignment by teacher is displayed and it can be submitted it with (Text Entry, Upload, WebURL, etc) if needed.
    See Reference: https://www.dropbox.com/s/zfpv1esrot5k129/Assignment_Submission.swf

**Comment by nucloud-agutierrez** [comment]
QA20151123: QA tested. Fixed in UAT Environment.
1. Login as Teacher (sqateacher@domain.com)
2. Create Assignment with special option for (Text Entry, Upload, WebURL, etc)
3. Login as Student (sqastudent@domain.com)
4.The created assignment by teacher is displayed and it can be submitted it with (Text Entry, Upload, WebURL, etc) if needed.

**Comment by nucloud-agutierrez** [comment]
QA20161127: QA tested. Fixed in PROD Environment.

1. Login as Teacher (amaliajoygutierrez@gmail.com)
2. Create Assignment with special option for (Text Entry, Upload, WebURL, etc)
3. Login as Student (sqastudent@domain.com)
4.The created assignment by teacher is displayed and it can be submitted it with (Text Entry, Upload, WebURL, etc) if needed.
