### ISSUE TITLE
[UC]Manage assignmentS - grading

### ISSUE THREAD

**Issue by lance-huang-nucloudglobal** [nucloudglobal/lms-ext#37]
FS: https://trello.com/c/RxWdbP59/26-s-37-functional-specification

**Comment by jbaltazar** [comment]
This is default feature of Canvas LMS, we can start testing this UC in our SQA and UAT Server without the help of TL - @apetitnucloud for deployment.

**Comment by nucloud-agutierrez** [comment]
QA20151123: QA tested. Fixed.

1. Login as Teacher (sqateacher01@domain.com)
2. Create Assignment with special option for (Text Entry, Upload, WebURL, etc)
3. Login as Student (condenastlmstest-three@yahoo.com.ph)
4.Tthe created assignment by teacher is displayed and it can be submitted it with (Text Entry, Upload, WebURL, etc) if needed.
5. Login as Teacher (sqateacher01@domain.com)
6. Teacher will grade it under "Conde Nast" -> "Course Navigation" -> "Grade" -> "Select Specific Student"
7. Login as Student (condenastlmstest-three@yahoo.com.ph)
8. Student will see the graded assignment and he/she can also see the assignment comment from teacher via inbox.

Reference: https://www.dropbox.com/s/gas159bcalos441/Assignment_Grading.swf

**Comment by ajmgutierrez** [comment]
QA20151123: QA tested. Fixed in UAT Environment.

1. Login as Teacher (sqateacher@domain.com)
2. Create Assignment with special option for (Text Entry, Upload, WebURL, etc)
3. Login as Student (sqastudent@domain.com) 
4.The created assignment by teacher is displayed and it can be submitted it with (Text Entry, Upload, WebURL, etc) if needed.
5. Login as Teacher (sqateacher@domain.com)
6. Teacher will grade it under "Conde Nast" -> "Course Navigation" -> "Grade" -> "Select Specific Student"
7. Login as Student (sqastudent@domain.com)
8. Student will see the graded assignment and he/she can also see the assignment comment from teacher via inbox.

**Comment by nucloud-agutierrez** [comment]
QA20151123: QA tested. Fixed in UAT Environment.

1. Login as Teacher (sqateacher@domain.com)
2. Create Assignment with special option for (Text Entry, Upload, WebURL, etc)
3. Login as Student (sqastudent@domain.com) 
4.The created assignment by teacher is displayed and it can be submitted it with (Text Entry, Upload, WebURL, etc) if needed.
5. Login as Teacher (sqateacher@domain.com)
6. Teacher will grade it under "Conde Nast" -> "Course Navigation" -> "Grade" -> "Select Specific Student"
7. Login as Student (sqastudent@domain.com)
8. Student will see the graded assignment and he/she can also see the assignment comment from teacher via inbox.

**Comment by nucloud-agutierrez** [comment]
QA20160127: QA tested. Fixed in PROD Environment.

1. Login as Teacher (amaliajoygutierrez@gmail.com)
2. Create Assignment with special option for (Text Entry, Upload, WebURL, etc)
3. Login as Student (sqastudent@domain.com) 
4.The created assignment by teacher is displayed and it can be submitted it with (Text Entry, Upload, WebURL, etc) if needed.
5. Login as Teacher (amaliajoygutierrez@gmail.com)
6. Teacher will grade it under "Conde Nast" -> "Course Navigation" -> "Grade" -> "Select Specific Student"
7. Login as Student (sqastudent@domain.com)
8. Student will see the graded assignment and he/she can also see the assignment comment from teacher via inbox.
