### ISSUE TITLE
[UC]Manage rubric

### ISSUE THREAD

**Issue by lance-huang-nucloudglobal** [nucloudglobal/lms-ext#4]

**Comment by nucloud-agutierrez** [comment]
QA20150803: QA tested. Fixed in TEST Environment.

Steps:

**Rubrics (Sub Account)**

1. Login as Top Account (agutierrez@nucloudglobal.com)
2. Click one of the Account (CondeNast)
3. click on one of the the Sub account ( SQA Sub Account 01)
4. In the account navigation, click on Rubrics.
5. Create, read, update or delete Rubrics (SQA Rubrics 01)
6. Include a defined outcome in a rubric (SQA Test Outcome 01)


**Rubrics (Sub Account - Academic Manager)**

1. Login as Academic Manager (sqamanager@domain.com)
2. Click on the Account (CondeNast)
4. Click on the Sub Account under the Account (SQA Sub Account 01)
5. In the sub account navigation, click on Rubrics.
6. Create, read, update or delete Rubrics (SQA Rubric (Academic Manager))
7. Include a defined outcome in a rubric (SQA Outcomes (Academic Manager))

**Rubrics (Sub Account - Academic Executive)**

1. Login as Academic Executive (sqaexecutive@domain.com)
2. Click on the Account (CondeNast)
4. Click on the Sub Account under the Account (SQA Sub Account 01)
5. In the sub account navigation, click on Rubrics.
6. Create, read, update or delete Rubrics (SQA Rubric (Academic Executive))
7. Include a defined outcome in a rubric (SQA Outcomes (Academic Executive))

**Rubrics (Sub Account - Academic Director)**

1. Login as Academic Director(sqadirector@domain.com)
2. Click on the Account (CondeNast)
4. Click on the Sub Account under the Account (SQA Sub Account 01)
5. In the sub account navigation, click on Rubrics.
6. Create, read, update or delete Rubrics (SQA Rubric (Academic Director))
7. Include a defined outcome in a rubric (SQA Outcomes (Academic Directorr))

**Rubrics (Course)**

1. Login a teacher's role (sqa02@teacher.com)
2. Click on one of the Course under the Sub Account "where the sub-account level outcome has been created" (SQA Course 01)
3. Click on the Assignment in the course-navigation
4. Create, read, update, delete Assignment (SQA Assignment 01)
5. Click Add Rubric button, then find and include rubric already defined at account level to the assignment.

**Comment by nucloud-agutierrez** [comment]
QA20150903: QA tested. Fixed in UAT Environment.

Steps:

**Rubrics (Sub Account)**

1. Login as Academic Manager (sqamanager@domain.com)
2. Click on the Account (CondeNast)
4. Click on the Sub Account under the Account (SQA Sub Account 01)
5. In the sub account navigation, click on Rubrics.
6. Create, read, update or delete Rubrics (SQA Rubric 01)
7. Include a defined outcome in a rubric (SQA Outcomes 01)

**Rubrics (Course)**

1. Login as Academic Manager (sqamanager@domain.com)
2. Click on one of the Course under the Sub Account "where the sub-account level rubric has been created" (SQA Course 01)
3. Click on the Assignment in the course-navigation
4. Create, read, update, delete Assignment (SQA Assignment 01)
5. Click Add Rubric button, then find and include rubric already defined at account level to the assignment SQA Rubric 01).

**Comment by nucloud-agutierrez** [comment]
QA20160127: QA tested. Fixed in PROD Environment.

Steps:

**Rubrics (Sub Account)**

1. Login as Academic Manager (sqamanager@domain.com)
2. Click on the Account (CondeNast)
4. Click on the Sub Account under the Account (SQA Sub Account 01)
5. In the sub account navigation, click on Rubrics.
6. Create, read, update or delete Rubrics (SQA Rubric 01)
7. Include a defined outcome in a rubric (SQA Outcomes 01)

**Rubrics (Course)**

1. Login as Academic Manager (sqamanager@domain.com)
2. Click on one of the Course under the Sub Account "where the sub-account level rubric has been created" (SQA Course 01)
3. Click on the Assignment in the course-navigation
4. Create, read, update, delete Assignment (SQA Assignment 01)
5. Click Add Rubric button, then find and include rubric already defined at account level to the assignment SQA Rubric 01).
