### ISSUE TITLE
Conde nast center logo is wrong

### ISSUE THREAD

**Issue by lance-huang-nucloudglobal** [nucloudglobal/lms-ext#40]
Expected result:
Shall be "Center",not "College", pls use logo same as ECW

SS:
Wrong:
![image](https://cloud.githubusercontent.com/assets/8621588/11140167/627354ac-8a12-11e5-8538-74abfbe56f2a.png)

Correct:
![image](https://cloud.githubusercontent.com/assets/8621588/11140169/67b796f8-8a12-11e5-9155-144dca2d9801.png)

**Comment by jbaltazar** [comment]
[Fix Pull Request Info](https://github.com/nucloudglobal/lms/pull/9)

<b>Dependencies: </b>
Should merge [EN-ZH-Version of Pull Request](https://github.com/nucloudglobal/lms/pull/8) first before merging the pull request to [Dev](https://github.com/nucloudglobal/lms/tree/dev) Branch.

**Comment by jbaltazar** [comment]
@apetitnucloud we hope that this fix will be implement asap. is this possible?
Note: This is not complicated code. Just image only

CC: @lance-huang-nucloudglobal

**Comment by nucloud-agutierrez** [comment]
QA20160108: QA tested. Fixed in TEST Environment.

![screen shot 2016-01-08 at 11 51 59 am](https://cloud.githubusercontent.com/assets/8049330/12190335/56dabd1c-b602-11e5-904b-0865dc7f6b08.png)

![screen shot 2016-01-08 at 11 52 43 am](https://cloud.githubusercontent.com/assets/8049330/12190337/5b0c23f8-b602-11e5-8194-30dcdcf7799f.png)

**Comment by lance-huang-nucloudglobal** [comment]
@apetitnucloud 
removed Code Review since code has been reviewed

CC @jbaltazar

**Comment by nucloud-agutierrez** [comment]
QA20150128: This UC is also fixed in PROD Environment.

**Comment by lance-huang-nucloudglobal** [comment]
lance set label PROD sqa verified
