### ISSUE TITLE
[UC]Manage question bank

### ISSUE THREAD

**Issue by lance-huang-nucloudglobal** [nucloudglobal/lms-ext#5]

**Comment by nucloud-agutierrez** [comment]
QA20150803: QA tested. Fixed in TEST Environment.

Steps:

**Question Banks (Sub Account)**

1. Login as Academic Manager (sqamanager@domain.com)
2. Click one of the Account e.g(CondeNast)
3. click on of the the Sub account in the account navigation
4. Click on the Sub Account Created (SQA Sub Account 01)
5. In the account navigation, click on Question Banks.
6. Create, read, update or delete grading (SQA Question Banks 01)

**Question Banks (Course)**

1. Login as Academic Manager (sqamanager@domain.com).
2. Click on one of the Course under the Sub Account "where the sub-account level outcome has been created" (SQA Course 01).
3. Click on the Quizzes in the course-navigation.
4. Create, read, update, delete Quizzes (SQA Quiz 01).
5. Click Questions tab.
6. User find question banks already defined at account level and add it into current course to use (SQA Question Banks 01).

**Comment by nucloud-agutierrez** [comment]
QA20150903: QA tested. Fixed in UAT Environment.

Steps:

**Question Banks (Sub Account)**

1. Login as Academic Manager (sqamanager@domain.com)
2. Click one of the Account e.g(CondeNast)
3. Click on of the the Sub account in the account navigation
4. Click on the Sub Account Created (SQA Sub Account 01)
5. In the account navigation, click on Question Banks.
6. Create, read, update or delete Question Banks (SQA Question Banks 01)

**Question Banks (Course)**

1. Login as Academic Manager (sqamanager@domain.com).
2. Click on one of the Course under the Sub Account "where the sub-account level question banks has been created" (SQA Course 01).
3. Click on the Quizzes in the course-navigation.
4. Create, read, update, delete Quizzes (SQA Quiz 01).
5. Click Questions tab.
6. User find question banks already defined at account level and add it into current course to use (SQA Question Banks 01).

**Comment by nucloud-agutierrez** [comment]
QA20150903: QA tested. Fixed in UAT Environment.

Steps:

**Question Banks (Sub Account)**

1. Login as Academic Manager (sqamanager@domain.com)
2. Click one of the Account e.g(CondeNast)
3. Click on of the the Sub account in the account navigation
4. Click on the Sub Account Created (SQA Sub Account 01)
5. In the account navigation, click on Question Banks.
6. Create, read, update or delete Question Banks (SQA Question Bank 01)

**Question Banks (Course)**

1. Login as Academic Manager (sqamanager@domain.com).
2. Click on one of the Course under the Sub Account "where the sub-account level question banks has been created" (SQA Course 01).
3. Click on the Quizzes in the course-navigation.
4. Create, read, update, delete Quizzes (SQA Quiz 01).
5. Click Questions tab.
6. User find question banks already defined at account level and add it into current course to use (SQA Question Bank 01).
