### ISSUE TITLE
[UC]Manage announcement

### ISSUE THREAD

**Issue by lance-huang-nucloudglobal** [nucloudglobal/lms-ext#6]

**Comment by nucloud-agutierrez** [comment]
QA20150803: QA tested. Fixed.

**Announcements (Course Level)**
**Roles: Academic executive, Academic manager**

1. Login as Academic Manager (sqamanager@domain.com)
2. Click one of the Account e.g(CondeNast)
3. Click on of the the Sub account in the account navigation
4. Click on the Sub Account Created (SQA Sub Account 01)
5. Click on one of the Course under the Sub Account "where the sub-account level outcome has been created" (SQA Course 01)
6. In the account navigation, click on Announcements.
7. Create, read, update or delete Announcements (SQA Announcement (Academic Manager))

**Comment by nucloud-agutierrez** [comment]
QA20150903: QA tested. Fixed in UAT Environment.

**Announcements (Course Level)**
**Roles: Academic executive, Academic manager**

1. Login as Academic Manager (sqamanager@domain.com)
2. Click one of the Account e.g(CondeNast)
3. Click on one of the the Sub account in the account navigation
4. Click on the Sub Account Created (SQA Sub Account 01)
5. Click on one of the Course under the Sub Account (SQA Course 01)
6. In the account navigation, click on Announcements.
7. Create, read, update or delete Announcements (SQA Announcement01)

**Comment by nucloud-agutierrez** [comment]
QA20160127: QA tested. Fixed in PROD Environment.

**Announcements (Course Level)**
**Roles: Academic executive, Academic manager**

1. Login as Academic Manager (sqamanager@domain.com)
2. Click one of the Account e.g(CondeNast)
3. Click on one of the the Sub account in the account navigation
4. Click on the Sub Account Created (SQA Sub Account 01)
5. Click on one of the Course under the Sub Account (SQA Course 01)
6. In the account navigation, click on Announcements.
7. Create, read, update or delete Announcements (SQA Announcement01)
