### ISSUE TITLE
[UC]Manage module

### ISSUE THREAD

**Issue by lance-huang-nucloudglobal** [nucloudglobal/lms-ext#7]

**Comment by nucloud-agutierrez** [comment]
QA20150728: QA tested. Fixed in TEST Environment.

*see attached test evidences*

![create grading schemes](https://cloud.githubusercontent.com/assets/8049330/8922416/38b54492-3515-11e5-9966-f8cd5e43b026.png)

![edit grading scheme](https://cloud.githubusercontent.com/assets/8049330/8922417/3d4f4034-3515-11e5-8b51-73720abaa200.png)

![delete grading scheme](https://cloud.githubusercontent.com/assets/8049330/8922420/42dcd2dc-3515-11e5-84a0-1be82df2baec.png)

![course level grading scheme](https://cloud.githubusercontent.com/assets/8049330/8922422/48b12226-3515-11e5-809f-82c6e1e22d1e.png)

![course level view - edit grading scheme](https://cloud.githubusercontent.com/assets/8049330/8922424/4d19901e-3515-11e5-8fcf-e80a0ac7d9a0.png)

![course level already defined grading scheme](https://cloud.githubusercontent.com/assets/8049330/8922427/527f958a-3515-11e5-8771-fa274dc49914.png)

**Comment by nucloud-agutierrez** [comment]
QA20150804: QA tested. Fixed in TEST Environment.

**Modules (Course Level)**
**Roles: Academic executive, Academic manager**

1. Login as Academic Manager (sqamanager@domain.com)
2. Click one of the Account e.g(CondeNast)
3. Click on one of the the Sub account in the account navigation
4. Click on the Sub Account Created (SQA Sub Account 01)
5. Click on one of the Course under the Sub Account (SQA Course 01)
6. In the account navigation, click on Modules.
7. Create, read, update or delete Modules(SQA Module (Academic Manager))
8. Click the Settings Gear of the module to be in an Edit mode.
9. Add a Requirement to the Module (SQA Quiz 01 and SQA Assignment 01)
10. Add another Module (SQA Module 01 (Academic Manager)) then add a pre-requisite.
11. Click View Progress button to see the student progress.

**Comment by nucloud-agutierrez** [comment]
QA20150907: QA tested. Fixed in UAT Environment.

**Modules (Course Level)**
**Roles: Academic executive, Academic manager**

1. Login as Academic Manager (sqamanager@domain.com)
2. Click one of the Account e.g(CondeNast)
3. Click on one of the the Sub account in the account navigation
4. Click on the Sub Account Created (SQA Sub Account 01)
5. Click on one of the Course under the Sub Account (SQA Course 01)
6. In the account navigation, click on Modules.
7. Create, read, update or delete Modules (SQA Module 01)
8. Click the Settings Gear of the module to be in an Edit mode.
9. Add a Requirement to the Module (SQA Quiz 01 and SQA Assignment 01)
10. Add another Module (SQA Module 01) then add a pre-requisite (SQA Module Prerequisites 1).
11. Click View Progress button to see the student progress.

**Comment by nucloud-agutierrez** [comment]
QA20160127: QA tested. Fixed in PROD Environment.

**Modules (Course Level)**
**Roles: Academic executive, Academic manager**

1. Login as Academic Manager (sqamanager@domain.com)
2. Click one of the Account e.g(CondeNast)
3. Click on one of the the Sub account in the account navigation
4. Click on the Sub Account Created (SQA Sub Account 01)
5. Click on one of the Course under the Sub Account (SQA Course 01)
6. In the account navigation, click on Modules.
7. Create, read, update or delete Modules (SQA Module 01)
8. Click the Settings Gear of the module to be in an Edit mode.
9. Add a Requirement to the Module (SQA Quiz 01 and SQA Assignment 01)
10. Add another Module (SQA Module 01) then add a pre-requisite (SQA Module Prerequisites 1).
11. Click View Progress button to see the student progress.
